<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Анализатор страниц</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Главная</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>

            </ul>
        </div>
    </nav>
</header>

<?php
function getStyleForAlert($messagesGroup) {
    if ($messagesGroup === 'success') {
        return 'alert-success';
    };
    if ($messagesGroup === 'warning') {
        return 'alert-info';
    };
    return 'alert-danger';
}

if (isset($messages)):
    foreach ($messages as $messagesGroup => $messagesOfGroup):
        foreach ($messagesOfGroup as $message): ?>
            <div class="alert <?= getStyleForAlert($messagesGroup)?>" role="alert"><?= $message?></div>
  <?php endforeach;
   endforeach;
endif; ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1></h1>
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row">
                    <div class="col-8">
                        <input
                                type="text"
                                name="url[name]"
                                value="<?= isset($inputedURL) ? $inputedURL : '';?>"
                                required
                                class="form-control form-control-lg<?=isset($badURL) ? ' is-invalid' : '';?>"
                                placeholder="https://www.example.com"
                        >
                        <?php if (isset($badURL)):?>
                            <div class="invalid-feedback">
                                Некорректный URL
                            </div>
                        <?php endif;?>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>

                </form>
                <form style="margin-top: 50px" action="/clearurls" method="post" class="row">
                    <input type="submit" class="btn btn-danger btn-lg ms-3 px-5 mx-3" value="Очистить таблицу urls">
                </form>
            </div>
        </div>
    </div>
</main>
<footer class="border-top py-3 mt-5 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>