<?php require 'parts/header.phtml'; ?>
<?php require 'parts/messagesOutput.phtml';?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1></h1>
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row">
                    <div class="col-8">
                        <input
                                type="text"
                                name="url[name]"
                                value="<?= isset($inputedURL) ? $inputedURL : '';?>"
                                required
                                class="form-control form-control-lg<?=isset($badURL) ? ' is-invalid' : '';?>"
                                placeholder="https://www.example.com"
                        >
                        <?php if (isset($badURL)):?>
                            <div class="invalid-feedback">
                                Некорректный URL
                            </div>
                        <?php endif;?>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>

                </form>
                <!--form style="margin-top: 50px" action="/clearurls" method="post" class="row">
                    <input type="submit" class="btn btn-danger btn-lg ms-3 px-5 mx-3" value="Очистить таблицы">
                </form-->
            </div>
        </div>
    </div>
</main>

<?php require 'parts/footer.phtml'; ?>