<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>

            </ul>
        </div>
    </nav>
</header>

<?php
function getStyleForAlert($messagesGroup) {
    if ($messagesGroup === 'success') {
        return 'alert-success';
    };
    if ($messagesGroup === 'warning') {
        return 'alert-info';
    };
    return 'alert-danger';
}

if (isset($messages)):
    foreach ($messages as $messagesGroup => $messagesOfGroup):
        foreach ($messagesOfGroup as $message): ?>
            <div class="alert <?= getStyleForAlert($messagesGroup)?>" role="alert"><?= $message?></div>
        <?php endforeach;
    endforeach;
endif; ?>


<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: https://mail.ru</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= $url['id']?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= $url['name']?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= $url['created_at']?></td>
                </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= $url['id']?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            <?php if (isset($urlChecks)):
                foreach ($urlChecks as $check):?>
                    <tr>
                        <td><?=$check['id']?></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><?=$check['created_at']?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif;?>
            </tbody>
        </table>
    </div>
</main>
<footer class="border-top py-3 mt-5 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>
</footer>
</body>
</html>
